version: '2'
services:
  mule-node1:
    container_name: mule-node-1
    build:
      context: .
      args:
        cluster_conf: mule-cluster-node-1.properties
    ports:
      - "8081:8081"
    volumes:
      - /Users/Shared/development/data/mule-docker/cluster/node1/apps:/opt/mule/apps
      - /Users/Shared/development/data/mule-docker/cluster/node1/logs:/opt/mule/logs
    networks:
      - cluster-net
  mule-node2:
    container_name: mule-node-2
    build:
      context: .
      args:
        cluster_conf: mule-cluster-node-2.properties
    ports:
      - "9081:8081"
    volumes:
      - /Users/Shared/development/data/mule-docker/cluster/node2/apps:/opt/mule/apps
      - /Users/Shared/development/data/mule-docker/cluster/node2/logs:/opt/mule/logs
    networks:
      - cluster-net
networks:
  cluster-net:
    driver: bridge