version: '2'
services:
  mule-node1:
    container_name: mule-node-1
    build:
      context: .
      args:
        cluster_conf: mule-cluster-node-1.properties
    ports:
      - "8081:8081"
    volumes:
      - ~/mule-cluster/node1/apps:/opt/mule/apps
      - ~/mule-cluster/node1/logs:/opt/mule/logs
      - ~/mule-cluster/node1/domains:/opt/mule/domains
    networks:
      - cluster-net
    environment:
      - NODE_ID=1
      - MULE_ENV=dev
  mule-node2:
    container_name: mule-node-2
    build:
      context: .
      args:
        cluster_conf: mule-cluster-node-2.properties
    ports:
      - "9081:8081"
    volumes:
      - ~/mule-cluster/node2/apps:/opt/mule/apps
      - ~/mule-cluster/node2/logs:/opt/mule/logs
      - ~/mule-cluster/node1/domains:/opt/mule/domains
    networks:
      - cluster-net
    environment:
      - NODE_ID=2
      - MULE_ENV=dev
networks:
  cluster-net:
    driver: bridge
